apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
	name: my-app
  spec:
	replicas: 1
	selector:
	  matchLabels:
	    app: my-app
	template:
	  metadata:
	    labels:
	      app: my-app
	  spec:
	    containers:
	    - name: my-app
	      image: "gcr.io/lumidetechtest/app-image:version1.0"
	      ports:
	      - containerPort: 80
	      env:
	      - name: PORT
value: 80